### ISSUE TITLE
RG350 1.7.9.6 ROGUE Firmware (forked from this repo) doesn't automount ext2 external sdcard to /media/sdcard

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RetroXFW#15]
I recently updated from Firmware 1.6 to the [1.7.9.6 "ROGUE" firmware](https://github.com/Ninoh-FOX/RG350-ROGUE-CFW/releases) as linked to by the official [RGHandhelds web site](https://www.rghandhelds.com/).

After doing so, my ext2-formatted external microsd card no longer gets automounted to `/media/sdcard` like it did under Firmware 1.6.  And there appears to be no `fstab` entry for it on the read-only system volume that would cause it to automount, either -- and because the volume containing `/etc/fstab` is read only, I can't add one!

To mount the external sdcard, I have to physically connect the RG350 to my PC using the USB-C cable, ssh into it, and then run `mount /dev/disk/by-label/sdcard /media/sdcard` to get it to mount, which is extremely non-ideal.

Why doesn't the external microsd automatically get mounted anymore?  Obviously the ext2 filesystem is still supported, because it mounts just fine manually.

**Comment by c0d3h4x0r** [comment]
I think I may have found my answer in `/etc/udev/rules.d/61-automount.rules`.  It doesn't supply a filesystem-specific options line for the `ext2` filesystem; it only does so for `vfat`, `exfat`, `ext3`, `ntfs`, and `ext4`.  This seems like a massive oversight.

**Comment by Ninoh-FOX** [comment]
The kernel don't has support to ext2 file system

**Comment by c0d3h4x0r** [comment]
> The kernel don't has support to ext2 file system

The older kernels did.  Why was support for it removed?

**Comment by Ninoh-FOX** [comment]
Because is an old file system. What problem has ext3/4?

But this is very easy of activate.

**Comment by StartNext-zz** [comment]
I have exactly the same problem. After updating to 1.7.9.6 "ROGUE" firmware the external microsd card reader is basically useless...and I wasted several hours trying to format (fat32,ntfs,ext4) and switching microsd cards wondering wtf is wrong. Would be great to get the auto-mount feature back again. The network connection via USB is broken,too. Can't get any connection on Windows10 only on LINUX.

**Comment by Ninoh-FOX** [comment]
fixed in the new release

**Comment by StartNext-zz** [comment]
> fixed in the new release

Thank you 👍

**Comment by StartNext-zz** [comment]
Still not working for me :( My microSD 16GB was formatted (exfat) with Windows 10.
When I insert the microSD in external slot nothing happens. Auto mount feature  still not working for me. microSD is working perfectly because I can mount the sdcard manually via terminal. Thats working fine but complicated.

Error log says:
kern.info kernel: mmc1:new high speed SDHC card at address...
kern.info kernel: mmcbblk1: unknown partition table

**Comment by StartNext-zz** [comment]
Okay, I tried it with a fresh formatted microSD with fat32. Auto mount doesn't work either :( Have to mount it manually

**Comment by StartNext-zz** [comment]
May be useful. I started with a fresh install from sd_image.bin. Since then auto mount is dead...

**Comment by Ninoh-FOX** [comment]
try to format the external microsd with the scripts format of the console, this work fine.

**Comment by c0d3h4x0r** [comment]
Once I converted my microsd from ext2 to ext3, and relabeled that volume name from my old preferred name (“RG350-Games”) to “microsd”, then it automounted just fine.

It just sucked that I had to figure all of this out the hard way, as my ext2-formatted microsd always worked fine before.  Folks shouldn’t have to reformat their microsd and recopy hundreds of gigs of content back to it just to be able to keep using the same thing that was working fine in a previous kernel.

Thank you for issuing the point update to add back the ext2 support!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ninoh-FOX** [comment]
If all work fine now, please, close the issue.

**Comment by StartNext-zz** [comment]
> try to format the external microsd with the scripts format of the console, this work fine.

not quite. if you format the card with fat32 script auto-mount doesn't work. microSD has to be formatted with the RG-350 script (exfat) then it indeed runs perfectly. To all people you can't format microSD card with Windows (fat32 or exfat)! It has to be formatted with scripts provided by RG350 1.7.9.6 ROGUE Firmware. Otherwise microSD card will not auto-mount!

@Ninoh-FOX You definitely should mention this in README because otherwise 
inexperienced users spend like several hours to figure this out.

 Big shout out to @c0d3h4x0r for bringing light into this matter 👍

**Comment by Ninoh-FOX** [comment]
Fat32 work fine too now, I am reupload the files (see the date)

**Comment by c0d3h4x0r** [comment]
>To all people you can't format microSD card with Windows (fat32 or exfat)! It has to be formatted with scripts provided by RG350 1.7.9.6 ROGUE Firmware. Otherwise microSD card will not auto-mount!

That makes zero sense.  The format should be the same no matter which OS or tool was used to perform the format.
